package tk.freetobuild.mcunified.gui.components;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import tk.freetobuild.mcunified.UnifiedMCInstance;
import tk.freetobuild.mcunified.curse.CurseModInfo;
import tk.freetobuild.mcunified.gui.dialogs.DialogInstallVersion;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;

/**
 * Created by liz on 6/30/16.
 */
public class ModPanel {
    public JPanel panel1;
    private JLabel modIcon;
    private JLabel modTitle;
    private JLabel modDescription;
    private JLabel pageButton;
    private JLabel downloadButton;

    public ModPanel(CurseModInfo info, UnifiedMCInstance instance) {
        $$$setupUI$$$();
        try {
            modIcon.setIcon(new ImageIcon(ImageIO.read(new URL(info.getIcon()))));
        } catch (IOException e) {
            e.printStackTrace();
        }
        modTitle.setText("<html><h3>" + info.getName() + " By " + info.getAuthor() + "</h3></h1ml>");
        modDescription.setText("<html><p>" + info.getDescription() + "</p></html>");
        pageButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE))
                    try {
                        Desktop.getDesktop().browse(new URI(info.getPage()));
                    } catch (IOException | URISyntaxException e1) {
                        e1.printStackTrace();
                    }
                else
                    JOptionPane.showMessageDialog(panel1, "Browsing is not supported on your system", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        downloadButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new DialogInstallVersion(instance, info).setVisible(true);
            }
        });
    }

    private void createUIComponents() {
        try {
            pageButton = new JLabelButton(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/curseinstaller/globe.png"))), new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/curseinstaller/globe:hover.png"))));
            downloadButton = new JLabelButton(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/curseinstaller/download.png"))), new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/curseinstaller/download:hover.png"))));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(panel2, gbc);
        modIcon = new JLabel();
        modIcon.setText("");
        panel2.add(modIcon, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel3, gbc);
        modTitle = new JLabel();
        modTitle.setText("Label");
        panel3.add(modTitle, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modDescription = new JLabel();
        modDescription.setText("Label");
        panel3.add(modDescription, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel4, gbc);
        downloadButton.setText("");
        panel4.add(downloadButton);
        pageButton.setText("");
        panel4.add(pageButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
